"""Finite, concrete first-run cards for a fresh Superboard workspace."""

STARTER_ITEMS = (
    ("Jetzt", "**1 · Start here · Meet Superboard**",
     "Press ▶ Agent once: it opens the introduction, explains the board, and stays here for questions.",
     "Agent: read `GC_BOARD_URL` and append `/welcome`. Open that same-origin introduction sheet in the user's browser when a local GUI is available (`open` on macOS, `xdg-open` on Linux); otherwise include the clickable URL in your reply. Then say plainly: `I opened your Superboard introduction. Read it, ask me anything here, then press ✓ Done.` Do not create files, settings or extra cards in this step. The sheet carries the longer explanation; this card's thread remains the place for follow-up questions.",
     "Open my Superboard introduction and stay here for questions."),
    ("Jetzt", "2 · Set up this workspace",
     "Confirm the workspace home, boundaries, context and useful board topics. Usually 1–3 minutes.",
     "Agent: report the active workspace path and visible contents. Adapt to what exists: if it is blank, explain the single-folder workspace idea and propose a small context/README.md plus 2–5 board topics; if it is a code repository, explain when the repo itself versus a higher-level home is the useful boundary. Ask which related folders matter and which are off-limits. Make the workspace a git repository if it is not one yet: run `git init`, add a `.gitignore` that leaves `.superboard/` caches out, and make one first commit — decide this and simply do it, no question needed, because a local history is what makes every later change diffable and revertible. Say in one line that you did it. Explain that durable context and memories are plain workspace files the user can inspect and change. Present every proposed file and topic before writing it. Use workspace-foundation when installed. If the user already worked in a too-narrow workspace, explain that restarting elsewhere does not move its cards, threads or spend history; offer an exact copy/recovery plan and wait for approval.",
     "Inspect this workspace and guide me through a small, useful foundation."),
    ("Jetzt", "3 · Add your first real to-do",
     "Create one ordinary card in My to-dos. Leave it manual or hand it to the agent.",
     "Agent: explain that a card is a normal to-do first: its title and body describe the outcome, its thread keeps any conversation, and ✓ Done removes finished work from the active view. Ask for one real current to-do and do not invent demo work. Create the approved card with `python3 .superboard/board_write.py --new-card '<title>' --topic 'My to-dos'`; never edit inbox/board.md directly. Then ask whether the user wants to keep it manual or press ▶ Agent for one safe first hand-off. Do not launch it silently. Offer more topics or cards only after this first one exists.",
     "Help me add one real to-do to My to-dos and decide whether it needs the agent."),
    ("Jetzt", "4 · Understand runs, threads and cache",
     "Keep one card and thread for one outcome. Start a new thread when the outcome changes.",
     "Agent: explain this using the current card as the example. A normal card can stay manual. ▶ Agent performs one round and normally continues the same provider session on the next round. The written card thread is durable; a prompt cache is only an efficiency and losing it loses no board history. ✂ New thread keeps the written history but starts a fresh provider session. Recommend it only when the user starts a different outcome or old context is actively getting in the way—not after every reply. Read `GC_BOARD_URL`, append `/onboarding-showcase#threads`, and offer that short illustrated version of the same explanation. End with two concrete examples and invite questions in this thread.",
     "Explain runs, threads, new threads and prompt caching using this card as the example."),
    ("Jetzt", "5 · Find settings and get help",
     "There is no settings maze: ask the Superboard Agent, or inspect the workspace files it proposes changing.",
     "Agent: show where the Superboard Agent entry lives in the interface and explain the support model plainly. For ordinary questions or changes, create a normal to-do or ask in the current card and use ▶ Agent. Topics, actions, routines, context and operating rules are plain workspace files; propose and preview changes before writing them. The Superboard/S-Agent menu exposes selected maintenance functions, not a complete settings screen. Answer the user's questions here; do not change configuration unless they ask for a specific change.",
     "Show me where to ask for help and how settings work in Superboard."),
    ("Jetzt", "6 · Check your agent and model setup",
     "Confirm the platform and model that already work, then add another only if you need one.",
     "Agent: identify the platform and run profile that completed this turn, and state plainly that it already works. Explain the selected default in one sentence. Inspect which supported alternatives—Claude Code or the experimental macOS Codex runner—are already installed and ready. OpenCode is not a supported runner in this release; say so instead of offering to configure it. Ask whether another supported platform or model profile would solve a real need. If yes, help set up that one platform including its provider/login and verify a tiny real run; if no, finish this card without creating extra setup. Keep durable context in workspace files so changing models does not split the user's memory.",
     "Check my current agent and model setup and help me keep it simple."),
    ("Jetzt", "7 · Set up your Cockpit",
     "Add 2–4 useful one-click actions to the Cockpit you already have.",
     "Agent: begin by saying that the Cockpit tab is already there — it ships with one action, ⬆️ Check for updates — so this card customizes an existing Cockpit rather than creating one. FIRST ensure exactly one follow-up card named `Cockpit extension · Add a useful recurring action` using `python3 .superboard/board_write.py --ensure-card ...`. Inventory installed workspace skills, configured MCP names and supported CLIs. Propose 2–4 executable actions, each with a label, one relevant zone, a complete mission, side effects and verified dependencies. Present one self-contained approval artifact before editing actions.json; after approval re-read it, preserve unrelated entries and remain idempotent on resume. After saving, show the user where the approved actions now sit in the Cockpit, next to the shipped update card.",
     "Inventory what is ready and help me approve my first two to four Cockpit actions."),
    ("Bald", "8 · Set up an email digest",
     "Connect available mail access, test one useful digest, and optionally make it a Cockpit action.",
     "Agent: ask what the digest should help the user notice and how often it should run. Find the mail access available to this workspace and use a matching email-digest skill when one is installed; its absence is not a blocker. Read a small recent sample, produce one real digest, and tune the format with the user. If they want to repeat it, create one complete Cockpit action after showing the exact proposed definition.",
     "Help me create and test one useful email digest."),
    ("Bald", "9 · Set up one routine",
     "Choose one daily or weekly prompt that should reliably return to the board.",
     "Agent: explain that rituals.json intentionally starts empty. Ask which one recurring moment the user tends to miss. Propose one daily or weekly footer prompt with a clear question, timing and useful proof. Write only the routine the user chooses, then show when and where it will appear.",
     "Show me how routines work and help me add one useful routine."),
    ("Bald", "10 · Set up an off-duty view",
     "Choose which existing topics disappear locally when Off Duty is switched on.",
     "Agent: ask what this board is for and which current topics should disappear off duty. Read `GC_BOARD_URL`, append `/onboarding-showcase#off-duty`, and show that short before/after briefing. Translate the answer into explicit `off_duty.hidden_topics` and `off_duty.visible_topics` arrays in board.config.json; unknown or future topics remain visible. Present the proposed arrays and ask before saving. The toggle changes only the local view; a restart applies the configuration.",
     "Help me preview and configure what the Off Duty view should hide."),
    ("Bald", "11 · Turn on night rest",
     "Optional and off by default: force an evening stop if you want a hard boundary.",
     "Agent: explain that most users should leave night rest off. Show the exact board.config.json opt-in: `\"night_pause\": {\"enabled\": true}`. Ask before editing and change only that setting. Explain that Superboard must be restarted before the change takes effect.",
     "Explain the optional night-rest boundary and turn it on only if I choose it."),
    ("Bald", "12 · Let Superboard learn from your threads",
     "After three or four days of real use, distill only recurring preferences supported by the threads.",
     "Agent: if this workspace has fewer than three or four days of real threads, explain why this step is intentionally too early and leave it open. Otherwise use workspace-learning when installed, or inspect this workspace's threads and finished cards directly. Report recurring jobs, corrections and unused actions. Propose only a small set of durable preferences for the user to approve and store in plain workspace files.",
     "Look at how I actually used this board and tell me what you should remember."),
    ("Bald", "13 · Get more from Superboard",
     "Optional · two minutes · what the Cockpit is and four things to simply ask for.",
     "Agent: read `GC_BOARD_URL` and append `/inspiration`. Open that same-origin page in the user's browser when a local GUI is available (`open` on macOS, `xdg-open` on Linux); otherwise include the clickable URL in your reply. It explains what the Cockpit is and shows four things people rarely think to ask for. Build nothing from it in this step. Afterwards ask which of the four sits closest to the user's real work; if they name one, propose a title and create one normal card with `python3 .superboard/board_write.py --new-card '<title>' --topic 'My to-dos'`. If none fits, close the card without creating anything.",
     "Show me what else I could ask Superboard for."),
    ("Geparkt", "14 · Finish Getting started",
     "Close onboarding only after every other step is completed or consciously skipped.",
     "Agent: inspect every other card in Getting started. If any is open, list only those and help the user choose whether to complete or deliberately skip them; do not mark them done. If all are done, summarize the resulting workspace in five short bullets and ask the user to press ✓ Done. The Done action archives the onboarding cards and removes the topic.",
     "Check whether onboarding is complete and help me close Getting started."),
)
