"""Finite, concrete first-run cards for a fresh Superboard workspace.

Eight cards, kept apart from My to-dos: real work comes first, setup is a short
checklist the user finishes or skips. Further setup is something to ask for in a
card, not a card of its own."""

STARTER_ITEMS = (
    ("Jetzt", "**1 · Start here · Meet Superboard**",
     "Press ▶ Agent once: it opens the introduction, explains the board, and stays here for questions.",
     "Agent: read `GC_BOARD_URL` and append `/welcome`. Open that same-origin introduction sheet in the user's browser when a local GUI is available (`open` on macOS, `xdg-open` on Linux); otherwise include the clickable URL in your reply. Then say plainly: `I opened your Superboard introduction. Read it, ask me anything here, then press ✓ Done.` Do not create files, settings or extra cards in this step. The sheet carries the longer explanation; this card's thread remains the place for follow-up questions.",
     "Open my Superboard introduction and stay here for questions."),
    ("Jetzt", "2 · Hand off your first real task",
     "Put one real task in My to-dos and press ▶ Agent on it. The result comes back to that card.",
     "Agent: look at My to-dos first. If the user or their installing agent already added cards there, name them, suggest the one that suits a first hand-off best and do not ask for another task. Otherwise ask for one real, current task and do not invent demo work. If the user has no idea, offer three kinds of first task that need no waiting and use their own material: summarize or answer questions about a document they point to, draft a reply or text they owe someone, or research a question they are stuck on. Create the approved card with `python3 .superboard/board_write.py --new-card '<title>' --topic 'My to-dos'`; never edit inbox/board.md directly. Before the first hand-off, say plainly in two sentences that a run uses this agent's own permissions in this workspace and counts against the user's own plan or usage. Do not start the run yourself: tell the user to open that card and press ▶ Agent. Explain that the reply arrives as a new turn on the same card, that a ❓ marks a question for them, and that a failed run keeps the card and its text, so they fix the one named cause and press ▶ Agent again on the same card.",
     "Help me put one real task in My to-dos and hand it off to the agent."),
    ("Jetzt", "3 · Set up this workspace",
     "Optional if your agent already did this during install. Confirms the workspace home, boundaries and context.",
     "Agent: first check whether the installing agent already set this workspace up (a context file, a git repository, topics beyond My to-dos and Getting started). If it did, summarize what exists in three short bullets, ask whether anything is missing, and otherwise tell the user to press ✓ Done; do not repeat the setup conversation. Otherwise report the active workspace path and visible contents. Adapt to what exists: if it is blank, explain the single-folder workspace idea and propose a small context/README.md plus 2–5 board topics; if it is a code repository, explain when the repo itself versus a higher-level home is the useful boundary. Ask which related folders matter and which are off-limits. Make the workspace a git repository if it is not one yet: run `git init`, add a `.gitignore` that leaves `.superboard/` caches out, and make one first commit — decide this and simply do it, no question needed, because a local history is what makes every later change diffable and revertible. Say in one line that you did it. Explain that durable context and memories are plain workspace files the user can inspect and change. Present every proposed file and topic before writing it. Use workspace-foundation when installed. If the user already worked in a too-narrow workspace, explain that restarting elsewhere does not move its cards, threads or spend history; offer an exact copy/recovery plan and wait for approval.",
     "Inspect this workspace and guide me through a small, useful foundation."),
    ("Bald", "4 · Understand runs, threads and cache",
     "Keep one card and thread for one outcome. Start a new thread when the outcome changes.",
     "Agent: explain this using the current card as the example. A normal card can stay manual. ▶ Agent performs one round and normally continues the same provider session on the next round. The written card thread is durable; a prompt cache is only an efficiency and losing it loses no board history. ✂ New thread keeps the written history but starts a fresh provider session. Recommend it only when the user starts a different outcome or old context is actively getting in the way—not after every reply. Read `GC_BOARD_URL`, append `/onboarding-showcase#threads`, and offer that short illustrated version of the same explanation. End with two concrete examples and invite questions in this thread.",
     "Explain runs, threads, new threads and prompt caching using this card as the example."),
    ("Bald", "5 · Find settings and get help",
     "There is no settings maze: ask the Superboard Agent. This card also checks which agent and model you run.",
     "Agent: show where the Superboard Agent entry lives in the interface and explain the support model plainly. For ordinary questions or changes, create a normal to-do or ask in the current card and use ▶ Agent. Topics, actions, routines, context and operating rules are plain workspace files; propose and preview changes before writing them. The Superboard/S-Agent menu exposes selected maintenance functions, not a complete settings screen. Answer the user's questions here; do not change configuration unless they ask for a specific change. Then check the agent setup: identify the platform and run profile that completed this turn, and state plainly that it already works. Explain the selected default in one sentence. Inspect which supported alternatives—Claude Code or the experimental macOS Codex runner—are already installed and ready. OpenCode is not a supported runner in this release; say so instead of offering to configure it. Ask whether another supported platform or model profile would solve a real need. If yes, help set up that one platform including its provider/login and verify a tiny real run; if no, finish this card without creating extra setup. Keep durable context in workspace files so changing models does not split the user's memory.",
     "Show me where to ask for help, how settings work, and which agent and model I run."),
    ("Bald", "6 · Set up your Cockpit",
     "Add 2–4 useful one-click actions to the Cockpit you already have.",
     "Agent: begin by saying that the Cockpit tab is already there — it ships with one action, ⬆️ Check for updates — so this card customizes an existing Cockpit rather than creating one. FIRST ensure exactly one follow-up card named `Cockpit extension · Add a useful recurring action` using `python3 .superboard/board_write.py --ensure-card ...`. Inventory installed workspace skills, configured MCP names and supported CLIs. Propose 2–4 executable actions, each with a label, one relevant zone, a complete mission, side effects and verified dependencies. Present one self-contained approval artifact before editing actions.json; after approval re-read it, preserve unrelated entries and remain idempotent on resume. After saving, show the user where the approved actions now sit in the Cockpit, next to the shipped update card.",
     "Inventory what is ready and help me approve my first two to four Cockpit actions."),
    ("Bald", "7 · Get more from Superboard",
     "Optional · what the Cockpit is, plus things you can simply ask for later: a mail digest, a routine, an off-duty view.",
     'Agent: read `GC_BOARD_URL` and append `/inspiration`. Open that same-origin page in the user\'s browser when a local GUI is available (`open` on macOS, `xdg-open` on Linux); otherwise include the clickable URL in your reply. It explains what the Cockpit is and shows four things people rarely think to ask for. Build nothing from it in this step. Afterwards ask which of the four sits closest to the user\'s real work; if they name one, propose a title and create one normal card with `python3 .superboard/board_write.py --new-card \'<title>\' --topic \'My to-dos\'`. If none fits, close the card without creating anything. Also list, one line each, the setups the user can ask for later in any card, and do none of them now: an email digest (one tested digest, optionally a Cockpit action); one daily or weekly routine (rituals.json starts empty); an off-duty view that hides chosen topics (`off_duty.hidden_topics` and `off_duty.visible_topics` in board.config.json, unknown or future topics remain visible, preview at `/onboarding-showcase#off-duty`); optional night rest (`"night_pause": {"enabled": true}`, off by default); and, after three or four days of real use, learning recurring preferences from the threads.',
     "Show me what else I could ask Superboard for."),
    ("Geparkt", "8 · Finish Getting started",
     "Close onboarding only after every other step is completed or consciously skipped.",
     "Agent: inspect every other card in Getting started. If any is open, list only those and help the user choose whether to complete or deliberately skip them; do not mark them done. If all are done, summarize the resulting workspace in five short bullets and ask the user to press ✓ Done. The Done action archives the onboarding cards and removes the topic.",
     "Check whether onboarding is complete and help me close Getting started."),
)
