"""Finite, concrete first-run cards for a fresh Superboard workspace."""

STARTER_ITEMS = (
    ("Jetzt", "**1 · Start here · Tour Superboard**",
     "Open the desktop walkthrough first. No agent run or model tokens are needed.",
     "This is a static product tour. Open the walkthrough from this card, see the real desktop layout, then tick the card off. Cards also work as ordinary manual to-dos: ▶ Agent is optional. When used, the selected CLI runs in auto mode and inherits its host access plus configured MCPs/providers. If anything is unclear, write the question in the thread and use ▶ Agent.",
     "I have a question about the Superboard tour."),
    ("Jetzt", "2 · Set up this workspace",
     "Confirm the workspace home, boundaries, context and useful board topics. Usually 1–3 minutes.",
     "Agent: report the active workspace path and visible contents. Adapt to what exists: if it is blank, explain the single-folder workspace idea and propose a small context/README.md plus 2–5 board topics; if it is a code repository, explain when the repo itself versus a higher-level home is the useful boundary. Ask which related folders matter and which are off-limits. Explain that durable context and memories are plain workspace files the user can inspect and change. Present every proposed file and topic before writing it. Use workspace-foundation when installed. If the user already worked in a too-narrow workspace, explain that restarting elsewhere does not move its cards, threads or spend history; offer an exact copy/recovery plan and wait for approval.",
     "Inspect this workspace and guide me through a small, useful foundation."),
    ("Jetzt", "3 · Add your first real to-dos",
     "Add 3–8 current to-dos, then hand one safe task to the agent. Usually 1–3 minutes.",
     "Agent: explain that title and body carry the assignment, the thread keeps the conversation, ▶ Agent performs a round, and Done removes finished work from the active view. A card can also remain a normal manual to-do. Ask for 3–8 real current to-dos and do not invent demo work. Propose topics, then create approved topics with `python3 .superboard/board_write.py --new-topic '<name>'` and cards with `--new-card '<title>' --topic '<topic>'`; never edit inbox/board.md directly. Help choose one safe first hand-off but do not launch it silently.",
     "Show me how one card works, then help me add my current to-dos and run one."),
    ("Jetzt", "4 · Understand agent runs and threads",
     "Learn when to use a manual to-do, ▶ Agent or ✂ New thread. No model tokens are needed.",
     "This is a static explainer in the walkthrough. A card can stay manual. ▶ Agent uses the standing thread and may resume the provider session; ✂ New thread keeps the written history but starts the next run with a fresh session and cold cache. Use a new thread when the outcome changes or old context has become baggage, not after every reply. Open the explainer from this card, then tick it off. Ask the agent only if a question remains.",
     "I have a question about runs, threads or prompt caching."),
    ("Jetzt", "5 · Check your agent and model setup",
     "Confirm the platform and model that already work, then add another only if you need one.",
     "Agent: identify the platform and run profile that completed this turn, and state plainly that it already works. Explain the selected default in one sentence. Inspect which supported alternatives—Claude Code or the experimental macOS Codex runner—are already installed and ready. OpenCode is not a supported runner in this release; say so instead of offering to configure it. Ask whether another supported platform or model profile would solve a real need. If yes, help set up that one platform including its provider/login and verify a tiny real run; if no, finish this card without creating extra setup. Keep durable context in workspace files so changing models does not split the user's memory.",
     "Check my current agent and model setup and help me keep it simple."),
    ("Jetzt", "6 · Set up your Cockpit",
     "Create 2–4 useful one-click actions from capabilities that are already available.",
     "Agent: begin by saying that the Cockpit tab is hidden until the first valid action is saved. FIRST ensure exactly one follow-up card named `Cockpit extension · Add a useful recurring action` using `python3 .superboard/board_write.py --ensure-card ...`. Inventory installed workspace skills, configured MCP names and supported CLIs. Propose 2–4 executable actions, each with a label, one relevant zone, a complete mission, side effects and verified dependencies. Present one self-contained approval artifact before editing actions.json; after approval re-read it, preserve unrelated entries and remain idempotent on resume. After saving, announce that the Cockpit tab has appeared and show where it is.",
     "Inventory what is ready and help me approve my first two to four Cockpit actions."),
    ("Bald", "7 · Set up an email digest",
     "Connect available mail access, test one useful digest, and optionally make it a Cockpit action.",
     "Agent: ask what the digest should help the user notice and how often it should run. Find the mail access available to this workspace and use a matching email-digest skill when one is installed; its absence is not a blocker. Read a small recent sample, produce one real digest, and tune the format with the user. If they want to repeat it, create one complete Cockpit action after showing the exact proposed definition.",
     "Help me create and test one useful email digest."),
    ("Bald", "8 · Set up one routine",
     "Choose one daily or weekly prompt that should reliably return to the board.",
     "Agent: explain that rituals.json intentionally starts empty. Ask which one recurring moment the user tends to miss. Propose one daily or weekly footer prompt with a clear question, timing and useful proof. Write only the routine the user chooses, then show when and where it will appear.",
     "Show me how routines work and help me add one useful routine."),
    ("Bald", "9 · Set up an off-duty view",
     "Choose which existing topics disappear locally when Off Duty is switched on.",
     "Agent: ask what this board is for and which current topics should disappear off duty. Read `GC_BOARD_URL`, append `/onboarding-showcase#off-duty`, and show that short before/after briefing. Translate the answer into explicit `off_duty.hidden_topics` and `off_duty.visible_topics` arrays in board.config.json; unknown or future topics remain visible. Present the proposed arrays and ask before saving. The toggle changes only the local view; a restart applies the configuration.",
     "Help me preview and configure what the Off Duty view should hide."),
    ("Bald", "10 · Turn on night rest",
     "Optional and off by default: force an evening stop if you want a hard boundary.",
     "Agent: explain that most users should leave night rest off. Show the exact board.config.json opt-in: `\"night_pause\": {\"enabled\": true}`. Ask before editing and change only that setting. Explain that Superboard must be restarted before the change takes effect.",
     "Explain the optional night-rest boundary and turn it on only if I choose it."),
    ("Bald", "11 · Let Superboard learn from your threads",
     "After three or four days of real use, distill only recurring preferences supported by the threads.",
     "Agent: if this workspace has fewer than three or four days of real threads, explain why this step is intentionally too early and leave it open. Otherwise use workspace-learning when installed, or inspect this workspace's threads and finished cards directly. Report recurring jobs, corrections and unused actions. Propose only a small set of durable preferences for the user to approve and store in plain workspace files.",
     "Look at how I actually used this board and tell me what you should remember."),
    ("Geparkt", "12 · Finish Getting started",
     "Close onboarding only after every other step is completed or consciously skipped.",
     "Agent: inspect every other card in Getting started. If any is open, list only those and help the user choose whether to complete or deliberately skip them; do not mark them done. If all are done, summarize the resulting workspace in five short bullets and ask the user to press ✓ Done. The Done action archives the onboarding cards and removes the topic.",
     "Check whether onboarding is complete and help me close Getting started."),
)
